name: go_router_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.4

  go_router: ^14.6.2

  animations: ^2.0.11
  flex_color_scheme: ^8.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.3.10


flutter:
  uses-material-design: true

  assets:
    - assets/
